export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_BY_CATEGORY_REQUEST = 'NEWS_BY_CATEGORY_REQUEST';
export const NEWS_BY_KEYWORD_REQUEST = 'NEWS_BY_KEYWORD_REQUEST';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_ERROR = 'NEWS_ERROR';
